overrides:
  "debug@4.4.2": "4.4.1"
  "chalk@5.6.1": "5.6.2"
  "ansi-regex@6.2.1": "6.2.2"
  "ansi-styles@6.2.2": "6.2.3"
  "color-convert@3.1.1": "3.1.0"
  "color-name@2.0.1": "2.0.0"
  "color-string@2.1.1": "2.1.0"
  "strip-ansi@7.1.1": "7.1.2"
  "slice-ansi@7.1.1": "7.1.2"
  "wrap-ansi@9.0.1": "9.0.2"
  "simple-swizzle@0.2.3": "0.2.2"
  "is-arrayish@0.3.3": "0.3.2"
  "error-ex@1.3.3": "1.3.2"
  "supports-color@10.2.1": "10.2.2"
