import { KnownAssetListRecord } from "@/types/types";

/**
 * Known Stellar assets and their Stellar Asset Contract (SAC) addresses on
 * Mainnet, sourced from the Stellar known-assets registry.
 *
 * Each entry maps to a row in the Known assets tab of the Smart contract list:
 *   - assetCode:  the asset code (e.g. "USDC")
 *   - entity:     the issuing entity / company (e.g. "Circle")
 *   - assetClass: the asset category (e.g. "Stablecoins", "RWA", "Native Crypto")
 *   - contract:   the asset’s SAC contract ID
 */
export const KNOWN_ASSETS: KnownAssetListRecord[] = [
  {
    assetCode: "XLM",
    entity: "Stellar Network",
    assetClass: "Stellar Lumen",
    contract: "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA",
  },
  {
    assetCode: "AUDD",
    entity: "Novatti",
    assetClass: "Stablecoins",
    contract: "CACXKRVCW7I6CWX6RS6ANFDKVCOUI2PB6LTDUROL3J3FMJCRZ4ZLQRF6",
  },
  {
    assetCode: "CHFD",
    entity: "Swiss Stablecoin AG",
    assetClass: "Stablecoins",
    contract: "CDLK7OYX2K6VF7337AUSG7Q5JO5H57ACIITET6KANWC7NBCNRCQG2V7K",
  },
  {
    assetCode: "EURAU",
    entity: "AllUnity",
    assetClass: "Stablecoins",
    contract: "CB44W727WSLHPXJ47A6DHF5D34RKWSOZAMEDXO3CF5TEEEQ2ZX4V3VRI",
  },
  {
    assetCode: "EURC",
    entity: "Circle",
    assetClass: "Stablecoins",
    contract: "CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV",
  },
  {
    assetCode: "EURCV",
    entity: "SG Forge",
    assetClass: "Stablecoins",
    contract: "CANKBYNNAYKEZXLB655F2UPNTAZFK5HILZUXL7ZTFR3NF6LKDSVY7KFH",
  },
  {
    assetCode: "EURS",
    entity: "Stasis",
    assetClass: "Stablecoins",
    contract: "CDJJQLCW6GFVUXJOXXONVC6KHPTY4RFMDKFBAP6SHWVKICXPRS4RSIKY",
  },
  {
    assetCode: "GYEN",
    entity: "GMO",
    assetClass: "Stablecoins",
    contract: "CA67EQNWGPGXHVT6E4HQ65WEV54KFDB6HJDHVCJM33VKZ7XKR5MN3KPJ",
  },
  {
    assetCode: "MXNe",
    entity: "Brale",
    assetClass: "Stablecoins",
    contract: "CAPW7JXJ6H6SGJ5MVM25356FAYOVT3ICZUIZRT4KGZHLUNMTWNMUI3RM",
  },
  {
    assetCode: "PYUSD",
    entity: "PayPal USD",
    assetClass: "Stablecoins",
    contract: "CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2",
  },
  {
    assetCode: "SBC",
    entity: "Brale",
    assetClass: "Stablecoins",
    contract: "CDVIS7WXSDUOTKAH3HEA7EAJGEZNJ5QJYDZ7KM7KN6CPVCJX2TLJJXSK",
  },
  {
    assetCode: "UAH",
    entity: "DCM",
    assetClass: "Stablecoins",
    contract: "CAYRSHFUI5O3DCM7D5Q5X4Z6ERTST46JPUGI5DLMZ5YYFPL3PJSZHN77",
  },
  {
    assetCode: "USD",
    entity: "Wisdom Tree",
    assetClass: "Stablecoins",
    contract: "CA6JHDJIYZPBLR2REJOPNBVZGBZBXFJSJ366PGPYIHWKC7CZOPWSMQRR",
  },
  {
    assetCode: "USDC",
    entity: "Circle",
    assetClass: "Stablecoins",
    contract: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
  },
  {
    assetCode: "USDGLO",
    entity: "Brale",
    assetClass: "Stablecoins",
    contract: "CB226ZOEYXTBPD3QEGABTJYSKZVBP2PASEISLG3SBMTN5CE4QZUVZ3CE",
  },
  {
    assetCode: "USDM1",
    entity: "Republic of the Marshall Islands",
    assetClass: "Stablecoins",
    contract: "CAC743NYRBMS76L2DCPAXZTOEF6EJPKPVEC5OX2SXY7HOWNXISSLUE2C",
  },
  {
    assetCode: "VCHF",
    entity: "VNX",
    assetClass: "Stablecoins",
    contract: "CDOZE45WZ67M6DNO577SKX3AG6N3I3Y6HZNA63APVYEAF2X6Q6P6V5G6",
  },
  {
    assetCode: "VEUR",
    entity: "VNX",
    assetClass: "Stablecoins",
    contract: "CDHNIO6IJ7EBFUDVALSE347YYNV3RKFB3Y5NZ3W4RH4QP4IS56MGSI5E",
  },
  {
    assetCode: "ZUSD",
    entity: "GMO",
    assetClass: "Stablecoins",
    contract: "CDANHN6OUDZNFWDCEU6ZWCIC4DPHVFXP3QPARHALFOF26HLC45JWRTWP",
  },
  {
    assetCode: "mZAR",
    entity: "Mesh BV",
    assetClass: "Stablecoins",
    contract: "CCUAACXMBHFT254KXNRGQPTZV3BFMO6F23HXFBO5KDXMNRTREZRTJGTI",
  },
  {
    assetCode: "SAFO",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CDGSC6BA4TCAOVSFQCUEHDMOIIHYYVNYBT6YEARS4MX3ITAHUINVGQHX",
  },
  {
    assetCode: "chfSAFO",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CAJD2IBSP7VO2VYJQUYJSOGPJINTUYV7MQITINXVPTIH3CCLCUENNMW4",
  },
  {
    assetCode: "eurSAFO",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CBOOCGZSVRSZFRE4U2NWR2B4RXYVJWRCBTGOUD2JPI2TDJPWMTJX7FZP",
  },
  {
    assetCode: "gbpSAFO",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CAGYRRKPFSWKM6SJOE4QAAVYMOSHMDS5WOQ4T5A2E6XNCU7LZZKUNQKP",
  },
  {
    assetCode: "GOLD",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CDQULNXLNTST3ERDKI2UXFUL64WGVJA4INLSYZCQLBI5KHQ4PSLFJI5S",
  },
  {
    assetCode: "BB1",
    entity: "Bitbond",
    assetClass: "RWA",
    contract: "CA6EZRSYJDDGN2W6IQPBTT624I6VIS7SS6OR6GPJQOOQT7GRKK5UTDRL",
  },
  {
    assetCode: "CRDT",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CBQDK4Y3B2RYUSXE6JYYTHB6AIW655FPGE4OW7A2BWDZXZ5RALQ3UK3P",
  },
  {
    assetCode: "WTSI",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CBBIDGSNGX43W6AEN32UFSLRTSM64MLNCXAHFCJV6PQYR5E6LV4IHPSS",
  },
  {
    assetCode: "JAAA",
    entity: "Centrifuge",
    assetClass: "RWA",
    contract: "CDV6U7OEVY6KUEJ4WNS63AYB6RFU3BAE7AZJOQ7LPH447C6NWUXEZZSO",
  },
  {
    assetCode: "SPKCC",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CDS2GCAQTNQINSCJUJIVBJXILKBWP5PU7LOBGHMP3X47QCQBFKPMTCNT",
  },
  {
    assetCode: "deJAAA",
    entity: "Centrifuge",
    assetClass: "RWA",
    contract: "CC64WBDGS6QQP22QTTIACYIXT3WF7BBQEYOQPLTP7GTKYY7PZ74QYGSL",
  },
  {
    assetCode: "eurSPKCC",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CDWOB6T7SVSMMQN5V3P2OPTBAXOP7DAZHGVW3PYTZIKHVFKN6TBSXR6A",
  },
  {
    assetCode: "CETES",
    entity: "Etherfuse",
    assetClass: "RWA",
    contract: "CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV",
  },
  {
    assetCode: "EUROB",
    entity: "Etherfuse",
    assetClass: "RWA",
    contract: "CCHXOH2JGL6KBO5VOHR6WD4ZQXI6CFMJ5F65XVSZ6P47Y7KVZSQIPN6J",
  },
  {
    assetCode: "EUTBL",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CBGV2QFQBBGEQRUKUMCPO3SZOHDDYO6SCP5CH6TW7EALKVHCXTMWDDOF",
  },
  {
    assetCode: "KIMMFTNR",
    entity: "Helix",
    assetClass: "",
    contract: "CCMYXMDKZYVA4UQSI2YTNOPHSKBRNI2YUOL4Q6OK4SGRF2EJXSOOW7V2",
  },
  {
    assetCode: "KIMMFTRI",
    entity: "Helix",
    assetClass: "RWA",
    contract: "CBSTE7NRY3V4NXYF34GUUE22IJ4PTOITYHQJEOPUPWN5HYSYQJPXEI7X",
  },
  {
    assetCode: "KMMFTNR",
    entity: "Helix",
    assetClass: "",
    contract: "CA4ILYCBEQQE2U6T66SS3VVAWBGBTMHWHI34JGQ3DDG5HC6E5SEH4XEI",
  },
  {
    assetCode: "KMMFTRI",
    entity: "Helix",
    assetClass: "RWA",
    contract: "CBADCA7WVJOFIIN7NG4PRVU3TUN2JZWZLKUVY74KORBLTZ3MYCAV7GMY",
  },
  {
    assetCode: "KTB",
    entity: "Etherfuse",
    assetClass: "RWA",
    contract: "CBAECV6UVDS6ZKPMC63MUYY4V7Q3KTHR7NLUFGVVGK7K3AQT475QTETP",
  },
  {
    assetCode: "TESOURO",
    entity: "Etherfuse",
    assetClass: "RWA",
    contract: "CD6M4R2322BYCY2LNWM74PEBQAQ63SA3DUJLI3L4225U4ZVCLMSCBCIS",
  },
  {
    assetCode: "UKTBL",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CDT3KU6TQZNOHKNOHNAFFDQZDURVC3MSTL4ML7TUTZGNOPBZCLABP4FR",
  },
  {
    assetCode: "TPT30",
    entity: "Realiz",
    assetClass: "RWA",
    contract: "CBUBVYRKTQLMDRUBPP6SH4GO33KZCEEYBIWB5AWNGKODP4A6KPKM2VJ4",
  },
  {
    assetCode: "CHS",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CALKAWFRZJIX4UFNPK2PEYUUWS2VOIAPS4PU7SSV7HK4PTFAQLJ52SAM",
  },
  {
    assetCode: "CHS",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CAXJP5XW37Q73N24YFVIHI475PJJC2TBJKJV3HPMITKANCJ77VPQBW2L",
  },
  {
    assetCode: "LDVM",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CDA3TFZNNDE2FL7EXM5MA3USLN5KCQRD2R5T6KQDHWDVZR2HR5YBNGND",
  },
  {
    assetCode: "LDVM",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CCWCNQ6PBZ6FQFOJPURTJCRL2IB7K5BFBT4AWDEQJLF7J6PRDBIQSQJK",
  },
  {
    assetCode: "MNO",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBGNGQVUKWZ5WBH5B4DCIWPO6ZFLO7NM6BWB5M6WQPVLSXOBBUI5AAJM",
  },
  {
    assetCode: "MNO",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBMNFCZ6XFISCZ56NGO5FVBQBK2CRFPQZQLQCEIRV7VSVG4HGE3HGP33",
  },
  {
    assetCode: "RIVN",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CCTIHHLL6Q2UQRYWG3PDWTKIO5STYJX7AD2UTTWPHEB53SRB3PKA7ZMJ",
  },
  {
    assetCode: "RIVN",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBNM7L7YGKIKM5LNRCCKTZ4E5NC4QUPCIT5IH4HAH5GLMSYEWOCY63FR",
  },
  {
    assetCode: "RSC",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBTYPYAI4W47NTHBM5N3TSMNF2VYF5MWLRTVN3LPKJIEOLMNBUCPND3B",
  },
  {
    assetCode: "RSC",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBVWKNOEBQUDW4YAEFLKZUIUZXTEYLFQ2BB4VYPOHJ4JVXHJNB6KJTOP",
  },
  {
    assetCode: "RSR",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBJKR3NVPIL4REW75PG7M7ZJIJJ62U7I4K52Y634G7AX5C4L5ADGDKLC",
  },
  {
    assetCode: "RSR",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CDH2A7S4J6ECQDL4K4BB5JCBF37DYYYFNNKM2VIRZV3IVZ5VAT55BVFR",
  },
  {
    assetCode: "RSRB",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CB7ID5RFSHXTXNGBRJBK4S2WQBD2WJQSNGY5FX6EYI7PITXEED5AI54W",
  },
  {
    assetCode: "RSRB",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CDTPLH4K7DCVCVEE5HQXAE2PFSW23SPYBKPMITWF3BYW3T32JZL5223J",
  },
  {
    assetCode: "SHR",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CARM2SLSX7N43DKAHOJXUKZOTL27PMRVOAVSIJABBPRWDNBEPYD63JH7",
  },
  {
    assetCode: "SHR",
    entity: "Red Swan",
    assetClass: "RWA",
    contract: "CBZNQF6LYJ3L6UNB4RSFAD2QVJVQYXN5CWU74T33UXCT7I52UD5GPKOB",
  },
  {
    assetCode: "EPXC",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCFDP2AJITAMHCV6EEMNA6HKRWYDTLYIPRXPUAEUO7T5SWDFMTSQDLUY",
  },
  {
    assetCode: "EQTY",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCP7YZJWB7C4MIHA7L23OVKUXUXQ3WVFEBOCIYPNIN4LSQPCA26IA6XW",
  },
  {
    assetCode: "LNGV",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CAK3GBT7P6ADHBRK3LH3VODDY4HYLYYXAP6PEH436FYID2VJKPKND64L",
  },
  {
    assetCode: "MODR",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCYPD6HRLXCXOT3ZSUJ4HYYBC7MLAYI7E3QEN4IC7H7FNB4PFDMQLHWL",
  },
  {
    assetCode: "SPX",
    entity: "Cometum",
    assetClass: "RWA",
    contract: "CBKNEK7R42VLLKUFQQKDTV4N3AL6TZY7VVVTX3BEXVHGQ2F7ZWAFJPHK",
  },
  {
    assetCode: "SPXU",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CBVCBEMVSVH73W7HZZHEMFYSYNF2ALRUFNSATHF2WXENW33BGF5FSTFR",
  },
  {
    assetCode: "BENJI",
    entity: "Franklin Templeton",
    assetClass: "RWA",
    contract: "CCDSDPD7FXB74PFB2SYCHGQRWLXQRYRTQSPCVSRJ7FAOLOUGWEYAXQ7A",
  },
  {
    assetCode: "BTC",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CDQKBG4ZEU66GA74A46OFPHRBMYLFZJVR7H35U777OE2Q2COURN6XGSM",
  },
  {
    assetCode: "ETH",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCZPGEJGSZVF7X5IVNR3KCEFNBJBZSOMH2MV5TXBWE7UXQSTZWDHJC7Y",
  },
  {
    assetCode: "FLTT",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCZ6ZWEO3KEA6PHTK56C6MEOHPVPBWZ7C3YUXR6SMBROPIEVXWICRY2L",
  },
  {
    assetCode: "JTRSY",
    entity: "Centrifuge",
    assetClass: "RWA",
    contract: "CBHOEKLWTB6HR2A3IXHIIMQG5FOXWXS6EG4Q5YJDRPMXPCX7M24CYR2O",
  },
  {
    assetCode: "TECH",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CDBYSQCKN644WWEJBPYDDTF2V5BDSJKC2EXVIEKLGHQSMKILY4IO2NCD",
  },
  {
    assetCode: "TIPS",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CC5XKPSET6QVWPL7EFUA7KXO6XLWPWXJKAGJC24MXW7EYVXQLUBV4OM5",
  },
  {
    assetCode: "USDY",
    entity: "Ondo",
    assetClass: "RWA",
    contract: "CB3YA656OYIHU57657I5KGSBRHE5I3OZU4VFC22PYAOANFZHEWNYGAGP",
  },
  {
    assetCode: "USTBL",
    entity: "Spiko",
    assetClass: "RWA",
    contract: "CARUUX2FZNPH6DGJOEUFSIUQWYHNL5AVDV7PMVSHWL7OBYIBFC76F4TO",
  },
  {
    assetCode: "USTRY",
    entity: "Etherfuse",
    assetClass: "RWA",
    contract: "CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR",
  },
  {
    assetCode: "WTGX",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CCDI4CNUSRI2UYQ2F44VVUB47WNYQL552SQLL5KT6JQHDTTOS4PAWQ5G",
  },
  {
    assetCode: "WTLG",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CAIDESHFY4QU4I7FNNROV2ADPFZCWMB3VDMLBT5DZYEKWGOLT4ODNS6I",
  },
  {
    assetCode: "WTST",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CACJVBOTJ22N224NILIACP6FM75XE5JXIV2PGWYIXJ5R3GW3YD5VVFVS",
  },
  {
    assetCode: "WTSY",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CATVJYIVZMI3FFCFLNNBUSR7UGLIOCMJRZJ5YZU4LOVWKPTC4VSQ2IQG",
  },
  {
    assetCode: "WTTS",
    entity: "Wisdom Tree",
    assetClass: "RWA",
    contract: "CBZ63YIHU3OOSP2JW3CHMXJ67T3Z3IU3NRSSJ4M53GFDIRR4YXKCEE36",
  },
  {
    assetCode: "deJTRSY",
    entity: "Centrifuge",
    assetClass: "RWA",
    contract: "CBI7UCH5KGSVQRO5H4SUCZUTZABCITZLRHQQZTWL2TK4RZ72TAR6IHRV",
  },
  {
    assetCode: "gBENJI",
    entity: "Franklin Templeton",
    assetClass: "RWA",
    contract: "CAZGJD4BG6RLFQIAGPDPSX3IR73CBSVDEIBUDQGDZ3RCGGSOYSVBDSM7",
  },
  {
    assetCode: "sgBENJI",
    entity: "Franklin Templeton",
    assetClass: "RWA",
    contract: "CA4JGI47NZ4DYZT6SIXFJU4TVJPKC7QHYQXLKUZ2C7BT3ZX4ZXHO6YIK",
  },
  {
    assetCode: "abBUSD",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CCEV44WRVTSNARRNMUPVVMPJNC7HXKJXXODQCH36XBEOQVF7CM6DZNWI",
  },
  {
    assetCode: "abUSDC",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CBNJ54GNIRXBRB2P7PVKI7LVUBVR4ATTK6QDPZZKHM47VAP3CSJ7VYNB",
  },
  {
    assetCode: "abUSDT",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CD3MJB5T7S2SCG7FEDUYO4KYOGVXZ4FZEBJG43OCPUXG2DTWOJ22OIGR",
  },
  {
    assetCode: "acUSD",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CAZJ6CGCKGIBGD2BBAHXU2RTXM252X7T2OOAXCZWKM4PRIUXVBG3XRJJ",
  },
  {
    assetCode: "aeDAI",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CBM76Q67ZGEQBKLHG4VOA37CBS3LY7CP54HD2SYRDC7SHAIXTXUC2R53",
  },
  {
    assetCode: "aeUSDC",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CC6EBYOGHV6Y4DRTQC43K5JXVVF5GFJT5X763LTXHCSZKBDYQ2CTU4RL",
  },
  {
    assetCode: "aeUSDT",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CBCMRCWWKAHLMS7WQX2TOMXJBCL45I2WCNCIWRCSCKQXWMZQVYSPXQAS",
  },
  {
    assetCode: "apUSDC",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CB7VCORLWN5N4ZUTKSK7OQN6JC5ENKBK6NSKUZDEEPFMJGMH3U6AAIK4",
  },
  {
    assetCode: "apUSDT",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CDV5AXARL6BNJKOT5TF7QRY6VC6NPKC7ORALAEFQ6HZZSF6X3VL5FSAA",
  },
  {
    assetCode: "asUSDC",
    entity: "Allbridge",
    assetClass: "Stablecoins",
    contract: "CD2XQB4EVZGM4UTT52PM4335S5BU43DCN2GJESJ5A6OOCWC23D5MD3C5",
  },
  {
    assetCode: "AQUA",
    entity: "Aquarius",
    assetClass: "Native Crypto",
    contract: "CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK",
  },
  {
    assetCode: "BLND",
    entity: "Blend",
    assetClass: "Native Crypto",
    contract: "CD25MNVTZDL4Y3XBCPCJXGXATV5WUHHOWMYFF4YBEGU5FCPGMYTVG5JY",
  },
  {
    assetCode: "USDx",
    entity: "FxDAO",
    assetClass: "Stablecoins",
    contract: "CDIKURWHYS4FFTR5KOQK6MBFZA2K3E26WGBQI6PXBYWZ4XIOPJHDFJKP",
  },
  {
    assetCode: "EURx",
    entity: "FxDAO",
    assetClass: "Stablecoins",
    contract: "CBN3NCJSMOQTC6SPEYK3A44NU4VS3IPKTARJLI3Y77OH27EWBY36TP7U",
  },
  {
    assetCode: "GBPx",
    entity: "FxDAO",
    assetClass: "Stablecoins",
    contract: "CBCO65UOWXY2GR66GOCMCN6IU3Y45TXCPBY3FLUNL4AOUMOCKVIVV6JC",
  },
  {
    assetCode: "oUSD",
    entity: "OrbitCDP",
    assetClass: "Stablecoins",
    contract: "CBZPEXQLJCGUYTAQRQ4FGCXUV5O4TZER5WSOMCGNDNIIO4EJ4FU5GQNZ",
  },
  {
    assetCode: "LSP",
    entity: "Lumenswap",
    assetClass: "Native Crypto",
    contract: "CBXE6V454EUYWVQCI4TCSOG4CSNPQ2BLYOTKAKXYFHO3KNVX4CXYCY2T",
  },
  {
    assetCode: "SSLX",
    entity: "Sl8",
    assetClass: "Native Crypto",
    contract: "CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4",
  },
  {
    assetCode: "SolvBTC",
    entity: "SolvFinance",
    assetClass: "Representational Crypto",
    contract: "CBIJBDNZNF4X35BJ4FFZWCDBSCKOP5NB4PLG4SNENRMLAPYG4P5FM6VN",
  },
  {
    assetCode: "abBNB",
    entity: "Allbridge",
    assetClass: "Representational Crypto",
    contract: "CBUQVUWV6TYMA2VPAZVKHHASIFNHKT4RP7D7XMBAEZ5UMGPZYIWUQC3G",
  },
  {
    assetCode: "acCELO",
    entity: "Allbridge",
    assetClass: "Representational Crypto",
    contract: "CCZW2OHF4X5G5HWGWXU7LHT5QXIYYMNCZG74YYCLO3DXDTIWF45RJ543",
  },
  {
    assetCode: "aeETH",
    entity: "Allbridge",
    assetClass: "Representational Crypto",
    contract: "CAAP5SVCSZBUC4VWR2FQTROXEIC3PGLAXCNFFGA22BJRNNK7AR5RUN3K",
  },
  {
    assetCode: "apMATIC",
    entity: "Allbridge",
    assetClass: "Representational Crypto",
    contract: "CDRRBUXO43BOQLUVZCRWUVEDIW56WC243RKYVKDCYZ6B5MQOR6N5TLTJ",
  },
  {
    assetCode: "asSOL",
    entity: "Allbridge",
    assetClass: "Representational Crypto",
    contract: "CDOYXOTUFLLST7JDECAMP64XSSOSVTHD4E6D7CHCKIO23VSVY5ECQNPA",
  },
  {
    assetCode: "BTC",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CAO7DDJNGMOYQPRYDY5JVZ5YEK4UQBSMGLAEWRCUOTRMDSBMGWSAATDZ",
  },
  {
    assetCode: "ETH",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CBH4M45TQBLDPXOK6L7VYKMEJWFITBOL64BN3WDAIIDT4LNUTWTTOCKF",
  },
  {
    assetCode: "xSolvBTC",
    entity: "SolvFinance",
    assetClass: "Representational Crypto",
    contract: "CAUP7NFABXE5TJRL3FKTPMWRLC7IAXYDCTHQRFSCLR5TMGKHOOQO772J",
  },
  {
    assetCode: "yBTC",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CB2XMFB6BDIHFOSFB5IXHDOYV3SI3IXMNIZLPDZHC7ENDCXSBEBZAO2Y",
  },
  {
    assetCode: "yETH",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CDYEOOVL6WV4JRY45CXQKOBJFFAPOM5KNQCCDNM333L6RM2L4RO3LKYG",
  },
  {
    assetCode: "yUSDC",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CDOFW7HNKLUZRLFZST4EW7V3AV4JI5IHMT6BPXXSY2IEFZ4NE5TWU2P4",
  },
  {
    assetCode: "yXLM",
    entity: "UltraCapital",
    assetClass: "Representational Crypto",
    contract: "CBZVSNVB55ANF24QVJL2K5QCLOAB6XITGTGXYEAF6NPTXYKEJUYQOHFC",
  },
  {
    assetCode: "AAULL1",
    entity: "Archax",
    assetClass: "RWA",
    contract: "CAEKZNWSP63PUURQ3NIBBBW7VN4ZKIDKGST37M74DUG5ETLETO4ZCTFY",
  },
  {
    assetCode: "ARS",
    entity: "Anclap",
    assetClass: "Stablecoins",
    contract: "CCD6H4LBTHAPY3NGEE6TLLRUSPJGX4K5XI2J6E4MUNDB5TNXEKC23H5B",
  },
  {
    assetCode: "ARST",
    entity: "Settle",
    assetClass: "Stablecoins",
    contract: "CCRPYMVKZLWGZHEDZ23FOE22E3T3HOCNP5Y2EFZFVRUVIXU5NJ7UNGV2",
  },
  {
    assetCode: "ARSX",
    entity: "Chronos",
    assetClass: "Stablecoins",
    contract: "CDFMLT27STN32KZTZGT4DAAD6Z6YYDODA5KTGZ2333RFJYM77MOXHOZ6",
  },
  {
    assetCode: "BRLT",
    entity: "Settle",
    assetClass: "Stablecoins",
    contract: "CDIA2WBXIDLXYNL4IU55K77BUZHTC5E65ZGCOXEAEJDIW4XLHZHCSC7X",
  },
  {
    assetCode: "CLPX",
    entity: "CLPX, S.A.",
    assetClass: "Stablecoins",
    contract: "CBDRPADR3KIBJNUBNRTTO4P7NO5RVPMYKRJB5YCZUZ6B66RKYK324UJY",
  },
  {
    assetCode: "EURC",
    entity: "MyKobo",
    assetClass: "Stablecoins",
    contract: "CBVDRT5474OBUEXF5MJB3UGQ5CG7CKGCAH5M4RV5NBCDJUBZ5OXHJLOU",
  },
  {
    assetCode: "IDRT",
    entity: "KBTrading",
    assetClass: "Stablecoins",
    contract: "CDYBK2X5ZEQ7ZNDN7IPWWMOQ6SWEJW4A4UE2PNDFDVCYNAXB64O4FNXX",
  },
  {
    assetCode: "KES",
    entity: "ClickPesa",
    assetClass: "Stablecoins",
    contract: "CBAANNZVSOH6I42ZVVFTVB2JNVSHVBYUDWGGJHB4BLCXARYTNN3ODU3F",
  },
  {
    assetCode: "KRW",
    entity: "KBTrading",
    assetClass: "Stablecoins",
    contract: "CALZDNKGQPSPD23YW4SLJRJ75AOSWCWIOYKYFIKJBKXSVMWPFYF74PTV",
  },
  {
    assetCode: "MBRL",
    entity: "Mercado Bitcoin",
    assetClass: "Stablecoins",
    contract: "CC5MUJYOPXGPDXJNOFG7SKLZSPDWJBTTSWUZEYPMTRJBJ3J6G5REPSVN",
  },
  {
    assetCode: "PEN",
    entity: "Anclap",
    assetClass: "Stablecoins",
    contract: "CCFS6UDFSR5OJIN45RQPUCZ5JTTU5TQOTIS6XKYKNWKC4TVR752BOWOF",
  },
  {
    assetCode: "QCAD",
    entity: "Stablecorp",
    assetClass: "Stablecoins",
    contract: "CCFRJICVMOTECZNIEKP6DETFTQMK3726NORE4ELLQHMKSCCHTCHNDR4U",
  },
  {
    assetCode: "RWF",
    entity: "ClickPesa",
    assetClass: "Stablecoins",
    contract: "CDJ2ZXLXJEN4O7JJDC2DKX524LFMKFVWV4M722CBE3KHPFJWQSHM3RQN",
  },
  {
    assetCode: "TRYB",
    entity: "KBTrading",
    assetClass: "Stablecoins",
    contract: "CBI5PFS3NQ6ZBXFO622DU5BNCPO2J7GW4XYN27DSA4YRTPJU63AQPDC7",
  },
  {
    assetCode: "TZS",
    entity: "ClickPesa",
    assetClass: "Stablecoins",
    contract: "CD2GNQFE3GRUY5LRE5WT26OQIUBUQ5YKRVDRQ3FWCW7A7NZAPPFIHFAY",
  },
  {
    assetCode: "XAF",
    entity: "Tempo",
    assetClass: "Stablecoins",
    contract: "CDN7CMIQKWF2KVZ4RW5TW34MMALQ66TFAWJKMDQJ24NWBLDIG7MXRAAA",
  },
  {
    assetCode: "XCHF",
    entity: "KBTrading",
    assetClass: "Stablecoins",
    contract: "CACFQEH2USDRGSBYFOVJMX4DMX7HMRYAYOV2IWR7XEX3DD3HYQEWPAAL",
  },
  {
    assetCode: "XSGD",
    entity: "KBTrading",
    assetClass: "Stablecoins",
    contract: "CBBEPK2EKUTFPHU3T5MYEOME25P2RTIRSNPR6VSOMU3SZ3HXIMORBNZU",
  },
  {
    assetCode: "AFR",
    entity: "Afreum DAO",
    assetClass: "Native Crypto",
    contract: "CCG27OZ5AV4WUXS6XTECWAXEY5UOMEFI2CWFA3LHZGBTLYZWTJF3MJYQ",
  },
  {
    assetCode: "BRAVE",
    entity: "Brave",
    assetClass: "Native Crypto",
    contract: "CDRQND5ZVDRBRPVYRS5ZWZO3YCEO5PMCFVRDHEFFJLU4SRMBS2TGYHKF",
  },
  {
    assetCode: "PHO",
    entity: "Phoenix",
    assetClass: "Native Crypto",
    contract: "CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32",
  },
  {
    assetCode: "SHX",
    entity: "Stronghold",
    assetClass: "Native Crypto",
    contract: "CCKCKCPHYVXQD4NECBFJTFSCU2AMSJGCNG4O6K4JVRE2BLPR7WNDBQIQ",
  },
  {
    assetCode: "MOBI",
    entity: "Mobius Network",
    assetClass: "Native Crypto",
    contract: "CATHRLMZW3JUIYSXYE4YAI3SBBBQGXYAP674RINGUBQLNFTCZHMI5XZJ",
  },
  {
    assetCode: "REAL8",
    entity: "REAL8",
    assetClass: "Native Crypto",
    contract: "CD5DHFTAIWW6EL5BDCIH4OM3XHB6K5DKCBHSTWTZZPSHQ3NVVEGFQIU3",
  },
  {
    assetCode: "RIO",
    entity: "Realio",
    assetClass: "Native Crypto",
    contract: "CB2XLDU74PIXO5DENULX53IIC3DMKGN2UM5IBGMSSI634IAQJ7O3Z3UQ",
  },
  {
    assetCode: "SCOP",
    entity: "Scopuly",
    assetClass: "Native Crypto",
    contract: "CCJVS6IVXAAXWCMFVK6QLWHZHR4RTVRSEZRQ53GOAEDN3VY2BLPVY72J",
  },
  {
    assetCode: "TEMPO",
    entity: "Tempo",
    assetClass: "Native Crypto",
    contract: "CAEIC7KZMYNQEHUHX5JO6Z3GBWRF2YTYPKDCWW2KZTSDUQG4SP5Q6EDO",
  },
  {
    assetCode: "TFT",
    entity: "Threefold",
    assetClass: "Native Crypto",
    contract: "CCXY3CNHSU2DPUOZFKNNH67IVRMBRCATX4SABDSLBY5LAJI66LRLHTJQ",
  },
  {
    assetCode: "VELO",
    entity: "Velo",
    assetClass: "Native Crypto",
    contract: "CAESLMGW5LYTIEJI7FJHK6SFSWRELLNVX5Q4WR4UZEALMTRWQDBKDPAG",
  },
  {
    assetCode: "XXA",
    entity: "Ixinium",
    assetClass: "Native Crypto",
    contract: "CBBJTE34KZHJACB2A6OXCRTDDLX4LI7GKYYD6XYJSGMX46BLNAG752HS",
  },
  {
    assetCode: "BTCLN",
    entity: "KBTrading",
    assetClass: "Representational Crypto",
    contract: "CBHIQPUXLFLC5O44ZJVUTCL5LMZFLVGU5DEIGSYKBSAPFMOGTKOQEPFM",
  },
  {
    assetCode: "ACREDIT04",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CDIVLG73XHRDXGDH5ITUZQY4FEPZKI74EE3LKZ2DOPU4Q2J7RG4SK4EU",
  },
  {
    assetCode: "ACREDIT05",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CA5WQ3WE7AIXLWPEAKT26QDXMKEF5HA5AORYVPHYCGTUJMCVP5UXA6LN",
  },
  {
    assetCode: "ACREDIT06",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CC7KNN6B2OL4LYEH5NAQ3FZMOUPFRMXKIN4QDCJNRGXO3KOPIQQCUPB6",
  },
  {
    assetCode: "BRPL01",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CATAOFFDBEVQJZYDJHE765CJYOH6KRVXAA2OPQ2LBZ5H5SHV4YTFN3N7",
  },
  {
    assetCode: "CARTAO56",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CADYRVOIC6Q4HSOR5K5QITFRA5BWV5O76BXYRLAHJP6QJMDJIGKKUVNX",
  },
  {
    assetCode: "CARTAO57",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CBEYZ2LLTDT774XCTN6LQNUPTIFWFVRCMPXXPAYESHBCUUUNSAZ57IW3",
  },
  {
    assetCode: "CHILLI09",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CCEIJLHVFQ5L2ON2ECXQRG4ZKVBNH2Q2XRXJ56MQRJU2KRKNTL6SMN2X",
  },
  {
    assetCode: "CHILLI10",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CBVMGG3OSWH3AQWA422JWYRUGR4KNDZ47FG4NC2ZP53BWJDROTTKHY3J",
  },
  {
    assetCode: "CHILLI11",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CCSXHZJLW3LUQ2FN7WBZSV6KXMYYYEAB3I3SBWCAIXAPD7UCWUCNYBHN",
  },
  {
    assetCode: "DUX30",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CDCLBQZ3XCFJTQGQLQGN6CPP2QXWJRMHIQEEFNLHUE5Z53AIGR6AOZB2",
  },
  {
    assetCode: "JEITTO36",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CBN5I6GPCZ4IUXXAMOQ3OHDK5BOYOSGMRTUGUJ2SW6OUTECSKK6WOJQC",
  },
  {
    assetCode: "JEITTO37",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CBB2PTKKPVQYKJOUDPAC4IBAUEE7IR66U2GXQ5PHYJD2IWYV2EQCROI7",
  },
  {
    assetCode: "MBCREDIT10",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CASPEHQACOJNCJQXF7YPWWDAVSPMLNTP3RNYO3WEYDNKEWPQG7WMCIDK",
  },
  {
    assetCode: "MBCREDSB10",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CD5LYYOGN55F2SPLQD4XDLZDSZLQTVBUV6Q32BK2H5N2OTE2Y4U6EDEW",
  },
  {
    assetCode: "MEDTKN04",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CCSX34CKWHXUUBFNZUEWXBMOX4CRLZGHBP2YM5UZ6OJD45P43BVTMOVW",
  },
  {
    assetCode: "POOLCP02",
    entity: "Mercado Bitcoin",
    assetClass: "RWA",
    contract: "CD77NM7FHKAPK6EEEPPM44JELY5VVOKZ2OX3VFVKUSF4CZPIPBSVFSLX",
  },
];
