// This file is auto-generated by scripts/fetch-network-limits.mjs
// DO NOT EDIT MANUALLY

export interface NetworkLimits {
  // Per-transaction limits
  tx_max_instructions: number;
  tx_memory_limit: number;
  tx_max_footprint_entries: number;
  tx_max_disk_read_entries: number;
  tx_max_write_ledger_entries: number;
  tx_max_disk_read_bytes: number;
  tx_max_write_bytes: number;
  tx_max_contract_events_size_bytes: number;
  contract_data_key_size_bytes: number;
  contract_max_size_bytes: number;

  // Ledger-wide limits
  ledger_max_instructions: number;
  ledger_max_disk_read_entries: number;
  ledger_max_disk_read_bytes: number;
  ledger_max_write_ledger_entries: number;
  ledger_max_write_bytes: number;
  ledger_max_txs_size_bytes: number;

  // State archival TTL extension parameters
  max_entry_ttl: number;
  min_temporary_ttl: number;
  min_persistent_ttl: number;

  // Resource fees (in stroops)
  fee_rate_per_instructions_increment: number;
  fee_read_ledger_entry: string;
  fee_write_ledger_entry: string;
  fee_read_1kb: string;
  fee_write_1kb: string;
  fee_tx_size_1kb: string;
  fee_historical_1kb: string;
  fee_contract_events_1kb: string;
  persistent_rent_rate_denominator: string;
  temp_rent_rate_denominator: string;
  live_soroban_state_size_window: string[];

  // Rent-related config parameters for computing fee_per_rent_1kb
  state_target_size_bytes: string;
  rent_fee_1kb_state_size_low: string;
  rent_fee_1kb_state_size_high: string;
  state_size_rent_fee_growth_factor: number;
}

export const MAINNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 200,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 17280,
  "min_persistent_ttl": 2073600,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "804919226",
    "805869590",
    "805971922",
    "806822934",
    "807735702",
    "808494950",
    "808927678",
    "809534094",
    "811298716",
    "812007288",
    "812793472",
    "813319412",
    "813587668",
    "814923956",
    "815828136",
    "816162332",
    "816680760",
    "817510368",
    "818993240",
    "819865529",
    "820665793",
    "821269449",
    "821960589",
    "822887483",
    "823234507",
    "823703627",
    "824586595",
    "825578883",
    "825824699",
    "826412459"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const TESTNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 200,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "646634618",
    "647757777",
    "648351799",
    "648358067",
    "648362247",
    "648612769",
    "648936890",
    "650018763",
    "650263281",
    "650477089",
    "650485893",
    "650684261",
    "650711533",
    "650734425",
    "650729009",
    "651286481",
    "651677850",
    "651662042",
    "651651346",
    "651623554",
    "651570980",
    "651575204",
    "651579908",
    "651589508",
    "651818663",
    "651863261",
    "652327460",
    "652534783",
    "652750198",
    "652747778"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const FUTURENET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 600000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 100,
  "tx_max_disk_read_entries": 100,
  "tx_max_write_ledger_entries": 50,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 600000000,
  "ledger_max_disk_read_entries": 500,
  "ledger_max_disk_read_bytes": 3500000,
  "ledger_max_write_ledger_entries": 250,
  "ledger_max_write_bytes": 143360,
  "ledger_max_txs_size_bytes": 133120,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 25,
  "fee_read_ledger_entry": "6250",
  "fee_write_ledger_entry": "10000",
  "fee_read_1kb": "1786",
  "fee_write_1kb": "3500",
  "fee_tx_size_1kb": "1624",
  "fee_historical_1kb": "16235",
  "fee_contract_events_1kb": "10000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909",
    "50347909"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const NETWORK_LIMITS: Record<string, NetworkLimits> = {
  mainnet: MAINNET_LIMITS,
  testnet: TESTNET_LIMITS,
  futurenet: FUTURENET_LIMITS,
} as const;
