---
name: "Stale PRs"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # approx 9:30am daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          debug-only: false
          days-before-stale: 60
          days-before-close: 7
          stale-pr-message:
            "This pull request is stale because it has been open for 60 days
            with no activity. It will be closed in 7 days if no further activity occurs."
          close-pr-message: "This pull request was closed because it has been stale for 7 days with no activity."
          stale-pr-label: stale

          remove-stale-when-updated: true
          delete-branch: true
